# ===================================================================
# Spring Boot configuration for the "prod" profile.
#
# This configuration overrides the application.yml file.
# ===================================================================

# ===================================================================
# Standard Spring Boot properties.
# Full reference is available at:
# http://docs.spring.io/spring-boot/docs/current/reference/html/common-application-properties.html
# ===================================================================
server:
  servlet:
    context-path: /api/v1

logging:
  level:
    ROOT: INFO
    com.file2chart: INFO

# ===================================================================
# Application specific properties.
# Add your own application properties here.
# ===================================================================

application:
  google:
    api-key: ${GOOGLE_API_KEY}




