# ===================================================================
# Spring Boot configuration.
#
# This configuration will be overridden by the Spring profile you use,
# for example application-dev.yml if you use the "dev" profile.
# ===================================================================

# ===================================================================
# Standard Spring Boot properties.
# Full reference is available at:
# http://docs.spring.io/spring-boot/docs/current/reference/html/common-application-properties.html
# ===================================================================
server:
  servlet:
    context-path: /api/v1

logging:
  level:
    ROOT: INFO
    com.file2chart: INFO

springdoc:
  api-docs:
    enabled: true
    path: /api-docs
  swagger-ui:
    enabled: true
    disable-swagger-default-url: true
    path: /docs
  show-actuator: true

spring:
  profiles:
    active: dev
  cors:
    allowed-origins:
      - http://localhost:8080
      - https://*.rapidapi.com
  servlet:
    multipart:
      enabled: true
      max-file-size: 200MB
      max-request-size: 200MB

# ===================================================================
# Application specific properties.
# Add your own application properties here.
# ===================================================================

application:
  google:
    api-key: ""




