# ===================================================================
# Spring Boot configuration.
#
# This configuration will be overridden by the Spring profile you use,
# for example application-dev.yml if you use the "dev" profile.
# ===================================================================

# ===================================================================
# Standard Spring Boot properties.
# Full reference is available at:
# http://docs.spring.io/spring-boot/docs/current/reference/html/common-application-properties.html
# ===================================================================
server:
  servlet:
    context-path: /

spring:
  profiles:
    active: dev
  servlet:
    multipart:
      enabled: true
      max-file-size: 50MB
      max-request-size: 50MB

springdoc:
  api-docs:
    enabled: true
    path: /api-docs
  swagger-ui:
    enabled: true
    disable-swagger-default-url: true
    path: /docs
    operations-sorter: alpha
    tags-sorter: alpha
  show-actuator: false
  writer-with-order-by-keys: true

management:
  endpoints:
    web:
      exposure:
        include=*: health

# ===================================================================
# Application specific properties.
# Add your own application properties here.
# ===================================================================
